import { Inter } from "next/font/google";
import "@/styles/styles.scss";
//import "./custom.css";
import "./globals.css";

import TopNav from "@/components/TopNav";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="container-fluid">
          <TopNav />
          {children}
        </div>
      </body>
    </html>
  );
}
